server:
    port: 8081

spring:
    application:
        name: mcsv-cines

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/mcsv_cines
        username: root
        password: password
#        #  driver-class-name: com.mysql.cj.jdbc.Driver
#        driver-class-name: org.mariadb.jdbc.Driver
#        url: jdbc:mariadb://localhost:3306/mcsv_usuarios
#        username: root
#        password: password

    jpa:
        hibernate:
            ddl-auto: update
        #database: mariabd
        database-platform: org.hibernate.dialect.MariaDBDialect

        #database-platform: org.hibernate.dialect.MySQL8Dialect
    security:
        jwt:
            secret-key: k7ehq9LLttTbATjmp82uAm1DjrGoUn5fGhWW8n9t64I=
            secret-expiration-time: 3600000

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8765/eureka/
        register-with-eureka: true
        fetch-registry: true